### PR TITLE
Support quoted fields.

### LINKED ISSUE #23: Bug ; in ""
Hi guys!

I found a possible bug. I'm importing a file with approximately 3000 lines, and strangely the result was not interpreted as expected. "Just like Excel", for example.

Debugging, I realized that csvToJson splits columns that are not meant to split.
Example:
ABC
test1;"test2;...";test3

In the case above, if I open it in Excel, I get the correct result:
image

In csvToJson, it interprets as 4 columns instead of 3. It splits ; even if you are inside "". I believe that the correct behavior would be to ignore these cases, because in my understanding the user wants to inform that it is text;

### PR DESCRIPTION
**Pull request by JustinHarshbarger**
Fixes #23

## Proposed Changes

Logic to allow quoted lines. This allows for delimiter to be in the quoted field.

### CODE REVIEW

**Comment by zirho** [comment]
```
$ ts-node src/index.ts
/Users/user/projects/prr/prr-client/packages/csv-json/node_modules/convert-csv-to-json/src/util/stringUtils.js:26
        if (values.length > 0) {
                   ^
TypeError: Cannot read properties of undefined (reading 'length')
    at StringUtils.hasContent (/Users/user/projects/prr/prr-client/packages/csv-json/node_modules/convert-csv-to-json/src/util/stringUtils.js:26:20)
    at CsvToJson.csvToJson (/Users/user/projects/prr/prr-client/packages/csv-json/node_modules/convert-csv-to-json/src/csvToJson.js:76:23)
    at CsvToJson.getJsonFromCsv (/Users/user/projects/prr/prr-client/packages/csv-json/node_modules/convert-csv-to-json/src/csvToJson.js:55:17)
    at CsvToJson.getJsonFromCsvStringified (/Users/user/projects/prr/prr-client/packages/csv-json/node_modules/convert-csv-to-json/src/csvToJson.js:47:21)
    at CsvToJson.generateJsonFileFromCsv (/Users/user/projects/prr/prr-client/packages/csv-json/node_modules/convert-csv-to-json/src/csvToJson.js:42:32)
    at Object.exports.generateJsonFileFromCsv (/Users/user/projects/prr/prr-client/packages/csv-json/node_modules/convert-csv-to-json/index.js:124:13)
    at Object.<anonymous> (/Users/user/projects/prr/prr-client/packages/csv-json/src/index.ts:8:4)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (/Users/user/projects/prr/prr-client/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zirho** [comment]
```
        if (values && values.length > 0) {
```

will do the trick in `stringUtils.js`

**Comment by JustinHarshbarger** [comment]
@zirho I was missing the return on my fall back to the standard string split. I reran the test and it looks good. Sorry for not running the tests before opening the PR. This was a quick thing I had done to support a csv I was parsing for work and all lines had a quote somewhere (so I didn't encounter my bug).

**Comment by iuccio** [comment]
@JustinHarshbarger  thank you so much for your PR. This feature is one of the most wanted. 
It would be great if you add some tests.

**Comment by JustinHarshbarger** [comment]
@iuccio 
I added some tests and a few improvements to my solution (stripping the quotes that are at start/end as well as escaped quotes).

**Comment by JustinHarshbarger** [comment]
@iuccio Did you have a chance to review the tests?

**Review by iuccio — APPROVED** [review]

**Comment by iuccio** [comment]
@JustinHarshbarger merged :+1: 
Grazie mille :-)

**Pull request merged**
